apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uui2srjmp-python
  janus-idp.io/tekton: uui2srjmp-python
  backstage.io/kubernetes-id: uui2srjmp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uui2srjmp-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
