apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uui2srjmp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uui2srjmp-python 
  name: uui2srjmp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uui2srjmp-python 
